### ISSUE TITLE
Compiling trouble

### ISSUE THREAD

**Issue by Baravantan** [teo666/Universal-Motor-Controller#2]
First of all thank you for sharing your work.
I tried to compile with the "TEST_MODE" option but I get an error and it doesn't compile.
Also, if I leave the option commented out, I can compile in, but when I feed the circuit, the motor slowly begins to accelerate whatever the position of the potentiometer.
I checked the input signals (ZCD, TACHO, POT) and they seems normal.

versione 1.0.2 | Arduino:1.8.12 (Linux), Scheda:"Arduino Nano, ATmega328P (Old Bootloader)"

**Comment by teo666** [comment]
Hi @Baravantan !
Thanks to you for use and improve this code. I hope it can be usefull for you.

1) I confirm the compile error, the problem was caused due to a wrong place regards macroes definition. I have updated the repo.
2) Have you set the speed limit values during start up? These value should be printed in console during board sturtup. Check them, if they are correct, try to enable test mode, change PID parameters and check if the motor react to these changes.

Let me know

**Comment by Baravantan** [comment]
Hi @teo666 and thanks for your reply.
I was unable to set the speed limits values because, on power ON, the motor begins to accelerate whatever the position of the potentiometer, until it reaches a dangerous rpm. then I cannot set the minimum and maximum desired values. Unfortunately, my knowledge of the software is somewhat limited.
I built a circuit following the diagram you published, and connected it to a motor recovered from a Bosch washing machine, not better identified. I measured the signals on the tachometer more carefully and I detected **168Vpp** (!!) 
![DS1Z_QuickPrint61](https://user-images.githubusercontent.com/11626439/92619525-4b5e2c80-f2ca-11ea-8dbc-574d2b55d9c6.png)
and, on PORTD pin3, a signal at 25+ kHz and **8 Vpp** which I think is too much for Arduino.
![DS1Z_QuickPrint59](https://user-images.githubusercontent.com/11626439/92618289-ddfdcc00-f2c8-11ea-9517-79f2b01bc954.png)
Then, I lowered the supply voltage of the OP amp from 9V to 5.5V, obtaining the same signal at the output but with the correct level.
![DS1Z_QuickPrint60](https://user-images.githubusercontent.com/11626439/92618292-de966280-f2c8-11ea-8aec-5237239dbcb9.png)
May be that my motor produces a too high TACHO signal, and saturate (or destroy!) the OP amp input?
I will do other tests. If you have any suggestion, please help me. Thanks

**Comment by teo666** [comment]
Hi @Baravantan 
I admin that my circuit is not perfect due I am a software engineer but  not electrical, it could be improved and if you have suggestion you are welcome.

The tacho circuit is intended to work in saturation, I use this method to convert the tacho signal into digital signal that is more
easy to analize in arduino thanks to interrups.

However you are describing an unexpected behavior in UMC. In fact when programming phase start the output pin should be disabled preventing motor to start spin.
In this phase the main line frequency is calculated and the output motor is directly drived by potentiometer value. So keeping potentiometer
at lowest value (or ground its input) should disable the output motor pin, and increasing the potentiometer value shoud give the ability to modulate motor speed whit no PID control.

So I think there should be upstream problem, and preceed by step, ensuring all circuits (and software) are working properly. First of all i suggest to make programming mode working proprerty. It is usefull cause its behavior is like a simple triac circuit and can be used to drive bulb lamp (no led or flourescent lamp) avoiding keep attention on motor speed.

I remember that to get in programming mode programming button must be pressed before arduino start booting, and keep it pressend until "Programming mode" appear in serial monitor.

At this point the main line frequency is calculated the result is printed on monitor (its  value is not printed ad frequency but as timer clock tick) and UMC ask to set limit speed values, with oscilloscope should be possible see on ZCD circuit output a signal as in following image. At this point tacho signal is useless (except if we continue with setting limit speed) and circuit could be used as a simple triac circuit.
![photo_2020-09-12_09-19-25](https://user-images.githubusercontent.com/14860353/92990051-196ee500-f4d9-11ea-91ec-d1b76a6262e6.jpg)

Are you able to confirm these step? 

PS: ZCD signal can be always measured to check it works properly, even in disconnected

The next step is check if arduino can trigger interrupt propertly
Obviously i take for granted that circuit is correct

**Comment by Baravantan** [comment]
Hi, @teo666 
Ok, I followed the suggested procedure:
By keeping S1 pressed at boot, it enters the programming mode correctly:
`Calculating frequency ...`
`Number of ticks per half period: 617`
`Programming mode`
`Release programming button, please`
BUT the motor always runs.
IF instead I press S1 when the sketch is running, with the POT at zero, the output goes to zero.

I tried, as suggested, to connect a light bulb instead of the motor (great suggestion!).
I took a couple of screenshots: ch1 ZCD (1 yellow) Pin2 || ch2 Pin OC (2 light blue) || ch3 ACL (3 fuchsia) || S1 OFF || POT 50% 
![ch1 ZCD Pin2 | ch2 Pin OC | ch3 ACL | S1 OFF | POT 50% | OffDelay](https://user-images.githubusercontent.com/11626439/93020077-e1a09400-f5e3-11ea-9e5a-24b2b3289924.png)
![ch1 ZCD Pin2 | ch2 Pin OC | ch3 ACL | S1 OFF | POT 50% | Voff](https://user-images.githubusercontent.com/11626439/93020083-e5ccb180-f5e3-11ea-97e0-2063b5cd4c6c.png)

the signal on OC (2) turns off after 640uS from the crossing of the zero of AC L (3), when the next half-wave has reached 50V, thus triggering the triac also for the next half-cycle and therefore leaving the output always on.
By holding S1 and turning the POT, the length of the signal on the OC changes to the left, but it always goes out in the same point, except when I turn the POT to zero: in this case the signal on the OC disappears completely, and then the output turns off .
What I would do, if I were able, is to anticipate the shutdown of OC (2) before the zero crossing.
What I don't understand is why the sketch on your circuit works, but on mine it doesn't.
I also double-checked the connections and tried to upload the sketch to Arduino UNO as well (I'm currently using Nano), with identical behavior.
I hope this information is somehow useful.
Thanks for your help.

**Comment by Baravantan** [comment]
Hi, @teo666 
Important update
I built a really rough circuit, with the aim of getting a signal when AC is below a certain voltage level, and then around the zero crossing. 
![zcd](https://user-images.githubusercontent.com/11626439/93047861-20772e00-f666-11ea-893d-dafbf813cfb6.png)
The pulse I get is not that great (1 yellow), but now the circuit works in dimmer mode!
The ZCD pulse now arrives before the zero crossing, and consequently also the OC pin signal (2 light blue) turns off before it, but obviously not the triac, which continues to conduct up to the ZC.
![DS1Z_QuickPrint77](https://user-images.githubusercontent.com/11626439/93047871-2705a580-f666-11ea-9664-b1d292cad140.png)
![DS1Z_QuickPrint78](https://user-images.githubusercontent.com/11626439/93047878-2967ff80-f666-11ea-96d0-02c56702fb33.png)
Obviously, the circuit now needs some fine tuning and some calculations; what do you think about it?

**Comment by Baravantan** [comment]
My idea (leaving the circuit as is) is to transform the output to the triac from variable to fixed width (some tens of µS) leaving unchanged the moment when it turns on. I tried to change it in the code, eg.
`if (tick_after_zcd > xx) {TURN_OFF_TRIAC (); triac_state = 0;}`
but I did not succeed.

**Comment by teo666** [comment]
Hi @Baravantan 
These images are extremely usefull because they describe the working princile, and help to find the error.


> By keeping S1 pressed at boot, it enters the programming mode correctly:
> `Calculating frequency ...`
> `Number of ticks per half period: 617`
> `Programming mode`
> `Release programming button, please`


Good!


Lets analize [this](https://user-images.githubusercontent.com/11626439/93020077-e1a09400-f5e3-11ea-9e5a-24b2b3289924.png) image, and exlude momentary the fuchsia channel.
The yellow signal represent ZCD output and light blue triac triggering signal.

The fact that light blue signal overlaps the yellow one is a desired behavior, and this confirm that the interrupt code
is working correctly. This overlap is caused by the fact that the software make sure that zero crossing point is reached correctly and it is effectively the correct one.
This mechanism is used to avoid that arduino recognize signal spikes in ZCD signal as wrong zero point.

The following block code is responsible of this behavior, increasing the value (10) in the condition will delay triac output switch off.
If 0 is used no correction will be used and falling edge of triac output will coincide with rising edge of ZDC signal, and using too much higher value will 
fall triac output switch off after the zero crossing point, thus making triac always on.

`if (zcd_error_correction > 10 && !found_correct_main_phase) {`
`   zcd_tick_log = tick_after_zcd;`
`   frequency_calc_added = 1;`
`   if (!my_digital_read(PIND, PROG_PIN) && !delay_allow) {`
`     delay_count++;`
`   } else {`
`     delay_count = 1;`
`     delay_allow = 0;`
`   }`
`   if (!delay_count) {`
`     delay_allow = 1;`
`   }`
`   tick_after_zcd = 0;`
`   // spegni il triac`
`   TURN_OFF_TRIAC();`
`   triac_state = 0;`
`   found_correct_main_phase = 1;`
` }`

The ZCD circuit that you have used confirm this situation, except the fact that it doesn't give a sqaure wave signal, we can see the same overlapping situation
in [this](https://user-images.githubusercontent.com/11626439/93047871-2705a580-f666-11ea-9664-b1d292cad140.png) image.

At this point cosider the [image](https://user-images.githubusercontent.com/11626439/93020077-e1a09400-f5e3-11ea-9e5a-24b2b3289924.png) with fuchsia channel.

My ZCD circuit is based on [this](https://dextrel.net/design-ideas-2/mains-zero-crossing-detector.html) and as the author explain it should
trigger around zero volt point. BUT previous image seems not to confirm this situation, in fact the yellow risign edge is shifted to the right.

So I can assert that ZCD is not working propertly. Your circuit insead is working correctly becuase the yellow spike is centered on zero point.

At this point we have many way to proceed, some are solutions, others dummies solutions:

Solution:
    Change ZCD circuit.

Dummy solutions:
    Turn off triac output signal earlier for example after triac has entered into conduction state (I don't consider this as solution becuase does not resolve the sync problem of ZCD signal)

**Comment by teo666** [comment]
> My idea (leaving the circuit as is) is to transform the output to the triac from variable to fixed width (some tens of µS) leaving unchanged the moment when it turns on. I tried to change it in the code, eg.
> `if (tick_after_zcd > xx) {TURN_OFF_TRIAC (); triac_state = 0;}`
> but I did not succeed.

I can suggest this fast, brutal and not tested code

`if (triac_state) {`
`TURN_OFF_TRIAC();`
` }`

and put it immediatly BEFORE this code (before triac hes been swiched on)

`if (tick_after_zcd >= output && !triac_state) {`
`    // accendi il triac`
`    TURN_ON_TRIAC();`
`    triac_state = 1;`
`  }`

Let me know
Teo

**Comment by Baravantan** [comment]
It finally works as expected! and leaving yours circuit and sw intact.
Solution:
Put the correct values of the components on the circuit.

![DS1Z_QuickPrint79](https://user-images.githubusercontent.com/11626439/93345156-2a05bf00-f83b-11ea-8c4c-1b67897ee76e.png)
![DS1Z_QuickPrint80](https://user-images.githubusercontent.com/11626439/93345440-7d780d00-f83b-11ea-8665-aea6495a2c25.png)

As I feared, this was human error: for reasons too long to explain, I put C2 100x the required value. I'm sorry.
"C2 forms together with R1 and R2 a first-order low pass filter (...) By decreasing the 1/f frequency of this filter (...) the ZC-pulse will be delayed in relation to the real mains zero crossings"

Thank you very much for the time you have dedicated to me to find the error, as well as your indications were very useful to understand how your circuit works.

Giovanni
